language: java
dist: trusty
services:
  - mysql
sudo: true
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - sudo echo binlog-format=ROW>>/etc/my.cnf
  - sudo echo log-bin=mysql-bin>>/etc/my.cnf
  - sudo service mysql reload
  - mysql -e 'CREATE DATABASE IF NOT EXISTS binlog_test;'
script: mvn -DargLine="-Dbinlog.user=root -Dbinlog.host=127.0.0.1 -Dbinlog.port=3306 -Dbinlog.schema=binlog_test" clean test-compile test